version: 0.0.1-alpha.{build}
skip_tags: true
skip_commits:
  files:
    - '**/*.md' # skip documentation
    - '**/.tf' # skip terraform

image: Visual Studio 2017
build: off
clone_folder: c:\gopath\src\github.com\MattHodge\terraform-provider-octopusdeploy

environment:
  GOPATH: c:\gopath
  GO111MODULE: on # Enable Go Module Support
  # Settings for Octopus Deploy cloud for integration testing
  OCTOPUS_URL:
    secure: jP+YI6rOk5iO1YYgTczw5GA5i2QrBHcfhxw9dRd0zUo=
  OCTOPUS_APIKEY:
    secure: rhHMBdDw0HiZtu1w5XmrNHXB8G37o827aHx0E+ufhSY=

install:
  - ps: choco install golang --version 1.11.4 --no-progress --confirm
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version

before_test:
  - ps:  Invoke-Expression ".\integration\appveyor_scripts\start_integration_tests.ps1"

after_test:
  # Build Binaries
  - ps: .\build.ps1 -BuildVersion $env:APPVEYOR_BUILD_VERSION

deploy:
  release: terraform-provider-octopusdeploy-v$(appveyor_build_version)
  description: 'Realse of terraform-provider-octopusdeploy'
  provider: GitHub
  auth_token:
    secure: QaEHKLv6eipcnuoao5ppCTb14AIkBAAO3TJR13JYpt9VaDifFCe1DiC6YGIkJXjV
  artifact: /.*\.zip/
  draft: false
  prerelease: true
  on:
    # release from master branch only
    branch: master

# # Uncomment to debug the build
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
