name: Publish binaries on release
on:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build
      uses: ./actions/builder
      env:
        GO111MODULE: "on"
    - name: Publish
      uses: docker://moonswitch/github-upload-release:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
