name: revive-lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
