name: Run integration tests against Octopus in a Docker container

on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    env:
      ACCEPT_EULA: "Y"
      ACCEPT_OCTOPUS_EULA: "Y"
      ADMIN_EMAIL: "john.bristowe@octopus.com"
      ADMIN_USERNAME: "admin"
      DB_CONNECTION_STRING: "Server=db,1433;Database=OctopusDeploy;User=sa;Password=Password01!"
      MASTER_KEY: "6EdU6IWsCtMEwk0kPKflQQ=="
      OCTOPUS_SERVER_BASE64_LICENSE: ${{ secrets.OCTOPUS_SERVER_BASE64_LICENSE }}
      OCTOPUS_SERVER_TAG: "latest"
      OCTOPUS_URL: "http://localhost"
      SA_PASSWORD: "Password01!"
      SQL_IMAGE: "mcr.microsoft.com/mssql/server"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: go build -v .

      - name: Start the Octopus container
        run: ./tests/start-octopus.sh

      - name: Generate an API key
        run: ./tests/Create-ApiKey.ps1
        shell: pwsh

      - name: Test
        run: go test -v ./octopusdeploy/...
